auto_tl1/urls.py
from django.urls import path
from auto_tl1 import views
from auto_tl1.views import GponApi
from login_app import views as view_login
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'auto_tl1'
urlpatterns = [
    path('', views.index, name='home'),
    path('cek/<str:cek_tipe>/<str:vendor_code>/', views.cekSN, name='ceksn'),
    path('ceksnunreg/<str:vendor_code>/', views.cekUnregSN, name='ceksnunreg'),
    path('ceksnreg/<str:vendor_code>/', views.cekRegSN, name='ceksnreg'),
    path('ceksnstat/<str:vendor_code>/', views.cekStatusSN, name='ceksnstat'),
    path('cekservice/<str:vendor_code>/', views.cekservice, name='cekservice'),
    path('wifiservice/<str:vendor_code>/', views.wifiService, name='wifi'),
    path('ceksto/', views.cekSto, name='ceksto'),
    path('config_gui/<str:vendor_code>/', views.config_gui, name='config_gui'),
    path('config/<str:vendor_code>/', views.config, name='config'),
    path('configbatch/', views.config_batch, name='config_batch'),
    path('deletebatch/', views.delete_config_batch, name='delete_config_batch'),
    path('verify_config/result/', views.resultConfig, name='result_config'),
    path('sop/<str:sop_tipe>/', views.sop, name='sop_batch'),
    path('cetak_pdf/<str:vendor_tipe>/', views.getPdf, name='cetakpdf'),
    path('export_excel/<str:vendor_tipe>/', views.getExcel, name='cetakexcel'),
    path('perangkat/<str:vendor_tipe>/', views.daftar_perangkat, name='perangkat'),
    path('status/nms/', views.serverNms, name='nms'),
    path('status/nossflog/', views.nossfLog, name='nossflog'),
    path('monitor/log/', views.cekLogApp, name='logapp'),
    path('monitor/log/tl1/<int:logappId>', views.cekLog, name='logtl1'),
    path('monitor/log/tl1/detail/<int:log_id>', views.cekLogDetail, name='logdetail'),
    path('monitor/tbuseractive/<str:sessionid>/', views.tbUserActive, name='tbuseractive'),
    path('monitor/useractive/', views.userActive, name='useractive'),
    path('monitor/useractive/terminate/', view_login.terminate, name='terminate'),
    path('login_api/', views.login_api, name='login_api'),
    path('gpon_all/', views.gpon_all_api, name='api_gpon'),
    path('gpon_get/<str:name_gpon>/', views.gpon_get_api, name='api_gpon_get')
]

login_app/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('login/', views.formLogin, name='formlogin'),
    path('login/choiceotp/', views.formPilihOTP, name='formOtp'),
    path('login/choiceotp/<str:tipe>', views.pilihOTP, name='pilihOtp'),
    path('login/gettoken/', views.getToken, name='getToken'),
    path('login/formtoken/', views.formToken, name='formtoken'),
    path('login/cektoken/', views.cekToken, name='cektoken'),
    path('login/proses_login/', views.loginView, name='proses_login'),
    path('logout/', views.logoutView, name='proses_logout'),
    path('session/flush/', views.flushSession, name='flush'),
]

sac/urls.py
from django.contrib import admin
from django.urls import path, include
from auto_tl1 import views as auto_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('auto_tl1.urls')),
    path('accounts/', include('login_app.urls')),
    path('', auto_views.index)
]

templates/cetak_perangkat.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>{{ page_title }}</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>{{ page_title }}</p>
            </div>
            <div>
                <div class='details'>
                    Date: {{ date }}
                    <hr class='hrItem' />

                </div>
            </div>
        </div>
    <table border="1">
        <tr style="padding-top: 5px">
            <th width="30px">No</th>
            <th>HOSTNAME</th>
            <th>IP GPON</th>
            <th>VLAN INTERNET</th>
            <th>VLAN VOICE</th>
            <th>STO</th>
            <th>SERVER</th>
        </tr>
        {% for gpon in gpons %}
            <tr style="padding-top: 5px">
                <td align="center">{{ forloop.counter }}</td>
                <td align="center" width="160px">{{ gpon.hostname }}</td>
                <td align="center" width="120px">{{ gpon.ip_gpon }}</td>
                <td align="center" width="100px">{{ gpon.vlan_inet }}</td>
                <td align="center" width="100px">{{ gpon.vlan_voice }}</td>
                <td align="center" width="120px">{{ gpon.sto }}</td>
                <td align="center" width="120px">{{ gpon.ip_server }}</td>
            </tr>
        {% endfor %}
    </table>
    </body>
</html>

templates/choiceotp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb" style="background-color: white">
        <li class="breadcrumb-item" style="background-color: white" aria-current="page"><span class="navbar-toggler-icon"></span></li>
      </ol>
    </nav>
    <main class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="jumbotron">
                        <div class="mx-auto social-container my-2 order-md-4">
                            <h3 class="text-center">Verivikasi 2 langkah</h3>
                            <br>
                            <a class="btn btn-primary mb-2 col-md-12" href="{% url 'login:pilihOtp' 'Telegram' %}">With Telegram</a>
                            <a class="btn btn-danger mb-2 col-md-12" href="{% url 'login:pilihOtp' 'Email' %}">With Email</a>
                        </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </main>

    {% for message in messages %}
        <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="messageModalLabel">Token</h5>
                <button type="button" class="close batal_modal_token" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body" id="pesan_modal_token">
                {{ message }}
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
    {% endfor %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% for message in messages %}
        <script>
            $('#messageModal').modal({
                'show' : true,
                'keyboard' : false
            });
        </script>
    {% endfor %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="mt-5 card-deck" style="margin:auto;">
                <div class="card border-primary mb-3" style="max-width: 18rem;">
                    <div class="card-body text-primary">
                    <h5 class="card-title">{{ all_devices }}</h5>
                    <div class="mr-3 text-right" style="font-size: 36px;">
                        <i class="fa fa-list fa-lg"></i>
                    </div>
                    </div>
                    <div class="card-footer bg-primary border-primary text-white">Total GPON</div>
                </div>

                <div class="card border-success mb-3" style="max-width: 18rem;">
                    <div class="card-body text-success">
                    <h5 class="card-title">{{ fh_device }}</h5>
                    <div class="mr-3 text-right" style="font-size: 36px;">
                        <i class="fa fa-hdd-o fa-lg"></i>
                    </div>
                    </div>
                    <div class="card-footer bg-success border-success text-white">GPON FIBERHOME</div>
                </div>

                <div class="card border-danger mb-3" style="max-width: 18rem;">
                    <div class="card-body text-danger">
                    <h5 class="card-title">{{ zte_device }}</h5>
                    <div class="mr-3 text-right" style="font-size: 36px;">
                        <i class="fa fa-list fa-lg"></i>
                    </div>
                    </div>
                    <div class="card-footer bg-danger border-danger text-white">GPON ZTE</div>
                </div>

                <div class="card border-warning mb-3" style="max-width: 18rem;">
                    <div class="card-body text-warning">
                    <h5 class="card-title">{{ hw_device }}</h5>
                    <div class="mr-3 text-right" style="font-size: 36px;">
                        <i class="fa fa-list fa-lg"></i>
                    </div>
                    </div>
                    <div class="card-footer bg-warning border-warning text-white">GPON HUAWEI</div>
                </div>
            </div>

            <h3 class="mt-4">Last Event</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Target Device</th>
                        <th>Action</th>
                        <th>Message</th>
                        <th>Status</th>
                        <th>Start Time</th>
                        <th>Stop Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in last_event %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'auto_tl1:logdetail' log.id %}">{{ log.target }}</a></td>
                        <td>{{ log.action }}</td>
                        <td>{{ log.status }}</td>
                        <td>{{ log.message }}</td>
                        <td>{{ log.time|date:'Y-m-d' }} {{ log.time|time:'H:i:s' }}</td>
                        <td>{{ log.stoptime|date:'Y-m-d' }} {{ log.stoptime|time:'H:i:s' }}</td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/log.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="mt-4">{{ page_title }}</h2>
            <table id="tb" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Target</th>
                        <th>Action</th>
                        <th>Status</th>
                        <th>Message</th>
                        <th>Start Time</th>
                        <th>Stop Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in logs %}
                    <tr>
                        <td><a href="{% url 'auto_tl1:logdetail' log.id %}">{{ log.target }}</a></td>
                        <td>{{ log.action }}</td>
                        <td>{{ log.status }}</td>
                        <td>{{ log.message }}</td>
                        <td>{{ log.time|date:'Y-m-d' }} {{ log.time|time:'H:i:s' }}</td>
                        <td>{{ log.stoptime|date:'Y-m-d' }} {{ log.stoptime|time:'H:i:s' }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/logapp.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2 class="mt-4">{{ page_title }}</h2>
            <table id="tb-logapp" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>
                        <th>Target</th>
                        <th>Action</th>
                        <th>Status</th>
                        <th>Start Time</th>
                        <th>Stop Time</th>
                        <th width="10px">IP Client</th>
                        <th>Username</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in logapp %}
                    <tr>
                        <td><a href="{% url 'auto_tl1:logtl1' log.id %}">{{ log.target }}</a></td>
                        <td>{{ log.action }}</td>
                        <td>{{ log.status }}</td>
                        <td>{{ log.time|date:'Y-m-d' }} {{ log.time|time:'H:i:s' }}</td>
                        <td>{{ log.stoptime|date:'Y-m-d' }} {{ log.stoptime|time:'H:i:s' }}</td>
                        <td>{{ log.ip_client }}</td>
                        <td>{{ log.username }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/logdetail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% for logdetail in logs %}
                <h2 class="mt-4">Log Detail {{ logdetail.target }} - {{ logdetail.action }} - {{ logdetail.username }} - {{ logdetail.ip_client }}</h2>
                <form>
                    <div class="form-group">
                        <label for="command">Command</label>
                        <input type="text" class="form-control" id="command" value="{{ logdetail.command }}" readonly>
                    </div>
                    <div class="form-group">
                        <label for="command_tl1">Command and Result from TL1 </label>
                        <div class="form-group">
                            <code>{% for detail in logdetail.logtl1_cmd.all %}{% if 'HUAWEI' in logdetail.action %}<pre>{{ detail.result_tl1 }}</pre>{% else %}{{ detail.command_tl1 }}{{ detail.result_tl1|linebreaks }}{% endif %}{% endfor %}</code>
                        </div>
                    </div>
                </form>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb" style="background-color: white">
        <li class="breadcrumb-item" style="background-color: white" aria-current="page"><span class="navbar-toggler-icon"></span></li>
      </ol>
    </nav>
    <main class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="jumbotron">
                    <h1>Login</h1>
                    <form action="{% url 'login:formOtp' %}" method="post">
                        {% csrf_token %}
                      <div class="form-group">
                        <label for="InputUsername">Username</label>
                        <input type="text" class="form-control" id="InputUsername" name="username" placeholder="Enter Username" required>
                      </div>
                      <div class="form-group">
                        <label for="InputPassword">Password</label>
                        <input type="password" class="form-control" id="InputPassword" name="password" placeholder="Password" required>
                      </div>
                        <div class="form-group">
                            <label for="captcha">Captcha Hitung {{ request.session.captcha1 }} + {{ request.session.captcha2 }} =</label>
                            <input type="number" class="form-control" id="capctha" name="capctha" required>
                        </div>
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </main>

    {% for message in messages %}
        <div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="messageModalLabel">Error</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                <div class="modal-body">
                    {{ message }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
                </div>
            </div>
        </div>
    {% endfor %}

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% for message in messages %}
        <script>
            $('#messageModal').modal({
                backdrop : 'static',
                keyboard : false
            });
        </script>
    {% endfor %}
</body>
</html>

templates/nossflog.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h1 class="display-4">{{ status }}</h1>

            {% if nossflog == 'empty'%}
                <script>
                    alert('Server Log NOSS-F sedang Down!!!');
                    history.go(-1);
                </script>
            {% else %}
                <pre>
                    {{ nossflog }}
                </pre>
            {% endif %}
        </div>
    <div class="col-md-3"></div>
    </div>
{% endblock %}

templates/perangkat.html
{% extends "base.html" %}
{% block content %}
    <h2 class="mt-4">{{ page_title }}</h2>
    <a class="btn btn-primary" href="{% url 'auto_tl1:cetakpdf' vendor_perangkat %}">Cetak PDF</a>
    <a class="btn btn-primary" href="{% url 'auto_tl1:cetakexcel' vendor_perangkat %}">Export Excel</a><br>
    <table id="tb_perangkat" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr align="center">
                <th>No</th>
                <th>HOSTNAME</th>
                <th>IP GPON</th>
                <th width="40px">VLAN INTERNET</th>
                <th width="40px">VLAN VOICE</th>
                <th>STO</th>
                <th>SERVER</th>
            </tr>
        </thead>
        <tbody>
            {% for gpon in gpons %}
                <tr align="center">
                    <td width="5px">{{ forloop.counter }}</td>
                    <td width="60px">{{ gpon.hostname }}</td>
                    <td width="40px">{{ gpon.ip_gpon }}</td>
                    <td>{{ gpon.vlan_inet }}</td>
                    <td>{{ gpon.vlan_voice }}</td>
                    <td width="30px">{{ gpon.sto }}</td>
                    <td width="30px">{{ gpon.ip_server }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

templates/result_config.html
{% extends 'base.html' %}
m
{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if hasil != '' %}
                <h1 class="display-4">Hasil</h1>
                {% if hw == True %}
                    <pre>
                        {{ hasil }}
                    </pre>
                {% else %}
                    <code>
                        {{ hasil|linebreaks }}
                    </code>
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/servernms.html
{% extends "base.html" %}
{% block content %}
    <h2 class="mt-4">{{ page_title }}</h2>
    <table id="tb_nms" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr align="center">
                <th>No</th>
                <th>HOSTNAME</th>
                <th>IP SERVER</th>
                <th>VENDOR</th>
                <th>STATUS</th>
                <th>Aksi</th>
            </tr>
        </thead>
        <tbody>
            {% for server in servers %}
                <tr align="center">
                    <td width="5px">{{ forloop.counter }}</td>
                    <td width="60px">{{ server.name }}</td>
                    <td width="40px" id="ip_server_{{ server.id }}">{{ server.ip_server }}</td>
                    <td width="30px">{{ server.vendor }}</td>
                    <td width="30px" id="status_nms_{{ server.id }}">{{ server.status }}</td>
                    <td width="30px">
                        <button class="btn btn-primary refresh" id="refresh_{{ server.id }}">
                            Refresh
                        </button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}